# Generated by Django 2.0.7 on 2018-07-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=220)),
                ('random_key', models.CharField(blank=True, max_length=15, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('exp_in_minutes', models.IntegerField(default=60)),
                ('expiry_timestamp', models.IntegerField(blank=True, default=None)),
            ],
        ),
    ]
