# Generated by Django 2.0.7 on 2018-07-03 22:48

from django.db import migrations, models
import shortner.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldata',
            name='url',
            field=models.CharField(max_length=220, validators=[shortner.validators.validate_url]),
        ),
    ]
