# Generated by Django 2.0.7 on 2018-07-03 23:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_auto_20180704_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldata',
            name='random_key',
            field=models.CharField(blank=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
